import type { TweetDocument } from './types'

export const sampleTweet: TweetDocument = {
  version: 2,
  author: {
    name: 'mǎNESY',
    handle: 'kongbaiming1230',
    avatarUrl: '/assets/kongbaiming1230-avatar.png',
    avatarCropX: 50,
    avatarCropY: 50,
    verification: 'blue',
    following: false,
    parody: false,
  },
  content: {
    text: '大家好呀，我是 @kongbaiming1230 👋\n欢迎使用我制作的 X推文截图生成器！你可以自由编辑推文内容和样式，一键导出高清图片。\n\n项目仅供娱乐与创作展示。喜欢的话欢迎关注我，也欢迎分享你的作品和建议！\n#关注kongbaiming1230 #X推文截图生成器',
    showMore: false,
    replyTo: '',
    publishedAt: '2026-09-07T10:30',
    automatedBy: '',
    translation: {
      enabled: false,
      sourceLanguage: '英语',
    },
  },
  media: {
    kind: 'images',
    layout: 'grid',
    activeIndex: 0,
    items: [
      { id: 'sea', src: '/assets/sea.svg', alt: '海边风景', width: 1200, height: 800, cropX: 50, cropY: 50 },
      { id: 'train', src: '/assets/train.svg', alt: '海边列车', width: 1200, height: 800, cropX: 50, cropY: 50 },
      { id: 'sunset', src: '/assets/sunset.svg', alt: '海边日落', width: 1200, height: 800, cropX: 50, cropY: 50 },
      { id: 'palms', src: '/assets/palms.svg', alt: '海边棕榈树', width: 1200, height: 800, cropX: 50, cropY: 50 },
    ],
  },
  quote: {
    enabled: false,
    author: {
      name: '城市漫游指南',
      handle: 'citywalks',
      avatarUrl: '/assets/quote-avatar.svg',
      avatarCropX: 50,
      avatarCropY: 50,
      verification: 'gray',
      following: false,
      parody: false,
    },
    text: '沿着海岸线走，风会替你收好今天的烦恼。',
    publishedAtLabel: '9月6日',
    translation: {
      enabled: false,
      sourceLanguage: '英语',
    },
    media: { kind: 'images', layout: 'grid', activeIndex: 0, items: [] },
  },
  reply: {
    enabled: false,
    author: {
      name: '远方的风',
      handle: 'distantbreeze',
      avatarUrl: '/assets/quote-avatar.svg',
      avatarCropX: 50,
      avatarCropY: 50,
      verification: 'none',
      following: false,
      parody: false,
    },
    text: '这组照片太治愈了，像把海风也带回来了。',
    publishedAtLabel: '2小时',
    metrics: {
      replies: 2,
      reposts: 1,
      quotes: 0,
      likes: 18,
      views: 860,
      bookmarks: 1,
      visible: true,
      expanded: false,
      liked: false,
      reposted: false,
      bookmarked: false,
    },
  },
  metrics: {
    replies: 128,
    reposts: 326,
    quotes: 28,
    likes: 1892,
    views: 52000,
    bookmarks: 46,
    visible: true,
    expanded: false,
    liked: false,
    reposted: false,
    bookmarked: false,
  },
  presentation: {
    mode: 'timeline',
    theme: 'light',
    locale: 'zh-CN',
    exportScale: 2,
    showMockup: true,
    canvasWidth: 600,
    zoom: 1,
  },
  extensions: [],
}
